apiVersion: apps/v1 # 배포 객체에 대한 API 버전
kind: Deployment    # 생성할 객체의 이름
metadata:
  name: catalog-service # 배포의 이름
  labels: # 배포에 추가할 레이블의 집합
    app: catalog-service # 이 배포는 "app=catalog-service" 라는 레이블을 갖는다
spec:
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service # 파드 이름
          image: ghcr.io/yeonnex/catalog-service # 컨테이너를 실행하기 위해 사용할 이미지. 태그가 정의되지 않으면 latest 가 암묵적으로 사용된다
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001 # 컨테이너에 의해 노출되는 포트
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata

# minikube image load catalog-service --profile polar